- fea-rs/src/bin/ttx_test.rs
- fea-rs/src/util/ttx.rs
If there is a XX.expected_diff file in the fonttools-tests file,
and if the diff of our ttx and the fonttools ttx exactly matches the
contents of this file, we will consider it a pass.
These files can be generated by the -d/--write-diff flag on the
ttx_test cli utility.
> Ability to save known-okay ttx diffs as passes

- fea-rs/Cargo.toml
- fea-rs/benches/parsing.rs
I want this in place so I can evaluate the impact of reparsing for
contextual rules.
> Add simple benchmark of parsing performance

- fea-rs/src/tests/parse.rs
This makes it easy to ensure that certain inputs will not parse,
and that we provide sane error messages for these cases.
> Add explicit testing for expected parse failures

- fea-rs/src/parse/context.rs
- fea-rs/src/parse/grammar/gpos.rs
- fea-rs/src/parse/grammar/gsub.rs
- fea-rs/src/parse/grammar/mod.rs
- fea-rs/src/parse/parser.rs
- fea-rs/src/tests/parse.rs
- fea-rs/src/token_tree.rs
- fea-rs/src/token_tree/rewrite.rs
- fea-rs/src/token_tree/token.rs
This adds the ability to optionally 'rewrite' nodes after the first parsing pass.
This is an opportunity to change the tree structure, but keeping all of the existing tokens. For instance, you might take a node with four children, and replace it with a node containing two children, each containing two of the original nodes.
This additional structure is important for things like contextual rules, so that we can group the input glyphs into backtrack/context/lookahead groups.
> Node rewriting

- fea-rs/src/bin/ttx_test.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/tests.rs
- fea-rs/src/tests/parse.rs
- fea-rs/src/tests/should_fail.rs
- fea-rs/src/util/ttx.rs
This includes some fixes to the error output when we validate the size
table, because that was being handled incorrectly.
This includes some refactoring so that more of the "compare this output
to that output" tests can share code.
> Compare output of error tests

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/token_tree/token.rs
- fea-rs/src/token_tree/typed.rs
- fea-rs/src/types.rs
- fea-rs/src/util.rs
This adds compilation of GSUB 5,6, and 8, and GPOS 7 & 8, including `ignore` statements.
This only generates chaining contextual lookups, even when there are no backtrack/lookahead items, and it has a number of other little quirks, but it's a reasonable starting point.
> Compile contextual rules

- fea-rs/Cargo.toml
- fea-rs/src/compile/lookups.rs
This also moves to pinning fonttools/otspec crates to a git revision,
which is a small step towards making this crate useable externally.
> Fixup rsub

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/tables.rs
- fea-rs/src/types.rs
If a GDEF table is not specified, we will infer glyph classes from defined mark classes and rules.
This also includes a few other tweaks related to GDEF:
- ignore `LigatureCaret` statements for any glyph that has a previous statement
- sort `LigatureCaret` values (which matches output from afdko & fonttools)
- handle GDEF `Attach` statements
> GDEF inference & tweaks

- fea-rs/Cargo.toml
- fea-rs/src/bin/compile.rs
- fea-rs/src/compile/output.rs
- fea-rs/src/util/ttx.rs
This updates the main binary to work with only a FEA file and a glyph ordering.
A glyph ordering is a text file with one glyph name per line. Lines preceded by '#' are ignored.
This is very bare bones, but should get us to a place where this can be used to compile tables.
> Compile with only FEA and a glyph ordering

- fea-rs/Cargo.toml
- fea-rs/src/bin/compile.rs
- fea-rs/src/compile/output.rs
- fea-rs/src/tests/compile.rs
- bump version
- update deps (and adjust to new API, in the case of xflags)
- pin to crates.io version of fontations
> Cleanup for 0.0.1 release

- fea-rs/src/bin/compile.rs
- fea-rs/src/compile/output.rs
- fea-rs/src/compile/tables.rs
- fea-rs/src/util/ttx.rs
This uses the new builder method on post to actually generate a post table before writing out our ttx; this is what feaLib does, and it clears up some funny little diffs in the test suite.
> Improve ttx output

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/output.rs
- fea-rs/src/compile/tables.rs
e.g. they're all suffixed with 'Builder', and I'm also cleaning up some of the old non-rustic names and removing associated `#[allow]` annotations.
> More consistent table builder names

- fea-rs/src/compile/compile_ctx.rs
Per 2.e.iv, a single value specified for a value record is interpreted as vertical advance when it occurs in four specific features.
closes #43
> Special handling for value records in vertical features

- fea-rs/src/compile/tables.rs
- fea-rs/src/compile/validate.rs
The spec says to do this but does not explain why, and fontTools has decided to allow it, so we will match them for now:
see https://github.com/fonttools/fonttools/pull/2675
> Do not ignore name ids 1-6

- fea-rs/src/compile/tables.rs
We were working correctly in the case where our input ended in a non-ascii character, but slightly less correctly otherwise. :|
> Consider finishing decoding name strings at some point

- fea-rs/src/compile/lookups/gsub.rs
This now matches the sorting behaviour of fontTools: longer sequences before shorter ones, and then in lexicographic order.
> Fixup ligature sub sort order

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/contextual.rs
- fea-rs/src/compile/lookups/gpos.rs
- fea-rs/src/compile/lookups/helpers.rs
- fea-rs/src/types.rs
This adds support for various subtable formats in contextual (and chain contextual) lookups.
A lot of this implementation uses feaLib as a reference.
Some funny stuff:
- for these subtables, fealib attempts to build all three formats, and then measures the final output size, picking the smallest. We adopt this as well, although it feels bad, and also doesn't tell the whole story; the final size of the generated binary depends on the tables it is compiled alongside, since this may provide the possibility of further space savings.
- Our size measurement code produces different results than does feaLib. In particular, in several tests our code will select format 3 over format 2 in places where feaLib does the opposite; this seems to be the result of us doing more efficient table packing.
> Contextual formats

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/types.rs
This is explicitly supported in the FEA spec, and explicitly forbidden in the OpenType spec, and apparently the FEA spec has won out.
> Support deleting glyphs ('sub X by NULL')

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/contextual.rs
- fea-rs/src/compile/lookups/gsub.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/parse/grammar/feature.rs
- fea-rs/src/token_tree/token.rs
- fea-rs/src/token_tree/typed.rs
This was one of the last major things I had avoided, and it ended up not being *too* bad. Basically we need to generate this after doing everything else, but we also need to insert the newly generated lookups at the front of the lookup list. This means all of our previously computed looup indices are now incorrect, so we have to go and adjust them all.
> Parse, validate, and compile the 'aalt' feature

- fea-rs/src/compile.rs
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/language_system.rs
- fea-rs/src/compile/lookups.rs
Another little bit of cleanup, letting us separate out logic related to tracking language systems.
This also adds a LanguageSystem type, to replace the tuple (Tag, Tag)
> Add compile::language_system module

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/features.rs
- fea-rs/src/compile/language_system.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/validate.rs
This is a complicated part of the spec, and there are numerous corner cases. This moves all the logic for determining how to assign lookups to scripts/languages into one place, in such a way that I can write unit tests against it.
> Refactor and clean up logic for assigning features to scripts/languages

- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/contextual.rs
we may want to revert this at some point, but for now we prefer matching feaLib as closely as possible.
see https://github.com/fonttools/fonttools/pull/2540
> Force GPOS7 to GPOS8, matching fonttools

- fea-rs/src/compile.rs
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/valuerecordext.rs
Here we want to treat all-zeros as a single zero advance (in x or y, depending on the containing feature) instead of as a null value record, which is the case in other contexts.
> Handle zero-value valuerecords in PairPos

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/contextual.rs
The spec says not to do that, but it is probably just a constraint of the original implementation, so once again we do what feaLib does.
> Include non-inline lookups in included aalt features

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/tables.rs
With this patch, we pass the `lookupflags.fea` test from fonttools.
mainly this means:
- correctly building all of GDEF, including the mark glyph set definitions and mark attach classdef
- reseting lookupflags on script statements, and ignoring redundant script statements
> Better handling of lookupflag

- README.md
- fea-rs/src/bin/compile.rs
With this patch, the compiler can now accept a single UFO file as input, and will use the public.glyphOrder lib key to determine the glyph order.
> Improve compiler

- fea-rs/src/bin/compile.rs
- fea-rs/src/compile.rs
- fea-rs/src/lib.rs
- fea-rs/src/tests/compile.rs
I want to add more helper methods in here, so instead of exporting various helpers at the top level, I would prefer to just have the module be public, and then the user can access methods through it.
> Make compile module public

- fea-rs/src/compile/lookups.rs
- fea-rs/src/util.rs
During initial development, I didn't know if I would be expecting features to have mixed GPOS/GSUB lookups, and my initial logic for dealing with them, if they occured, was naive to the point of useless.
This reworks that logic to be much more robust, splitting lookups manually if needed.
> More robust lookup splitting

- fea-rs/src/bin/compile.rs
- fea-rs/src/compile.rs
- fea-rs/src/compile/opts.rs
- fea-rs/src/compile/output.rs
- fea-rs/src/tests/compile.rs
- fea-rs/src/types/glyph_map.rs
- fea-rs/src/util/ttx.rs
This is the start of being a bit more disciplined about how we compile output. I do need to redo our compilation stuff at some point soon, but this is maybe a reasonable start?
The particular motivation here is that in order to have our ttx output match fonttools, we need to generate a post table. I was doing this in a hacky way in the ttx test binary, but I'd also like this option to be available during general compilation.
> Add compile::Opts, make 'generate post table' an option

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/contextual.rs
- fea-rs/src/tests/compile.rs
This was inpsired by realizing that it was possible to have a chain rule that referenced a named lookup of the incorrect type.
To handle this, I now require the user to be explicit when converting a LookupId to a u16 about whether they are in a GPOS or GSUB context; this ensures that if lookupids somehow end up in the wrong place, we will at least crash.
> Ensure no mixing of gsub/gpos lookups

- fea-rs/src/util/ttx.rs
As of https://github.com/fonttools/fonttools/pull/2950, a number of test cases that we had disabled have been modified in such a way that we can handle them correctly.
This updates the tests submodule, and removes those tests from the "do not run" list.
> Update fonttools tests

- fea-rs/src/bin/ttx_test.rs
- fea-rs/src/util/ttx.rs
Always control verbosity with FEA_VERBOSE
Previously the ttxt_test binary took a -v flag, whereas running tests via cargo test required setting an env var. Now everything is env var.
> Print warnings from ttx tests if FEA_VERBOSE set

- fea-rs/Cargo.toml
- fea-rs/src/bin/compile.rs
- fea-rs/src/bin/parse_test.rs
- fea-rs/src/bin/ttx_test.rs
This brings in log & env_logger, although it does not use them much. Most of our errors are reported through the diagnostics mechanism, but logging will be useful going forward.
> Set up logging

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/parse/context.rs
- fea-rs/src/parse/grammar/gsub.rs
- fea-rs/src/parse/grammar/mod.rs
- fea-rs/src/token_tree.rs
- fea-rs/src/token_tree/rewrite.rs
- fea-rs/src/token_tree/typed.rs
This is a rollup of commits of me addressing a number of lingering FIXMEs & TODOS.
- add a trait to generalize the backtrack/input/lookahead pattern common to various AST nodes
- verify that we have the correct range when reporting unresolved include statements
- validate the input of the OS/2 FamilyClass field
- disallow 'by NULL' in rsub rules
- support GSUB1 rules that omit the 'by' clause.
> Clean up fixmes

- fea-lsp/src/document.rs
- fea-rs/benches/parsing.rs
- fea-rs/src/bin/compile.rs
- fea-rs/src/bin/highlight.rs
- fea-rs/src/bin/parse_test.rs
- fea-rs/src/lib.rs
- fea-rs/src/parse.rs
- fea-rs/src/parse/context.rs
- fea-rs/src/parse/grammar/mod.rs
- fea-rs/src/parse/source.rs
- fea-rs/src/token_tree.rs
- fea-rs/src/token_tree/cursor.rs
- fea-rs/src/util/highlighting.rs
- fea-rs/src/util/paths.rs
- fea-rs/src/util/ttx.rs
This patch introduces a new trait, `SourceResolver`, which abstracts out the task of finding and loading the FEA for a given path, both for the root source as well as for any additional sources referenced by `include($source)` statements.
The logic around includes in FEA is complicated; depending on the implementation, include statements may be resolved relative to the *root* fea file, to the *including* file, or to a parent directory. Previously this resolution logic was spread out across various places; it now is generally isolated to the internal `FileSystemResolver` type.
This PR really started to get away from me; I have some more changes I now want to make around what types are exposed via the public API, but I want to checkpoint this here now before it balloons any further.
closes …
> Support in-memory compilation

- fea-rs/benches/parsing.rs
- fea-rs/src/bin/compile.rs
- fea-rs/src/compile.rs
- fea-rs/src/compile/compiler.rs
- fea-rs/src/compile/error.rs
- fea-rs/src/compile/output.rs
- fea-rs/src/diagnostic.rs
- fea-rs/src/lib.rs
- fea-rs/src/parse.rs
- fea-rs/src/parse/context.rs
- fea-rs/src/parse/source.rs
- fea-rs/src/parse/tree.rs
- fea-rs/src/tests/compile.rs
- fea-rs/src/util/paths.rs
- fea-rs/src/util/ttx.rs
This introduces a new builder-style API that can handle the entire compilation process.
Basic usage looks like,
```rust
let my_font_bytes = Compiler::new("path/to/features.fea", &glyph_map).compile_binary().unwrap();
```
Getting this to work well required reworking our error types, and doing that motivated a refactor to make `ParseTree` cheaply cloneable; doing this means that we can have an error type that contains some set of `Diagnostic` messages along with the `ParseTree` required to format them correctly.
I imagine we will run into some rough edges on this over time, but I hope this is at least the general outline of our API going forward.
> Compiler API

- fea-rs/src/compile/compiler.rs
- fea-rs/src/compile/error.rs
- fea-rs/src/parse/source.rs
- fea-rs/src/parse/tree.rs
- fea-rs/src/util/ttx.rs
This was a bit interesting. In order to make this work,
- I changed SourceLoadError to not store the inner error, since Arc<T> is only Send if T: Sync, and then we run into the problem where we can't create a SourceLoadError with a non-Sync inner error; so now we just store a message as an Arc<str>.
- I also changed the DiagnosticSet type to not store the whole parse tree, but just the source list, which is apparently all we actually need to format our errors.
- yolo
> Make CompilerError: Send

- fea-rs/Cargo.toml
Unblocks https://github.com/googlefonts/fontmake-rs/pull/123 which is currently stuck on 
mismatched types
struct write_fonts::font_builder::FontBuilder and struct FontBuilder have similar names, but are actually distinct types
perhaps two different versions of crate write_fonts are being used?rustcClick for full compiler diagnostic
Because fea-rs is on 0.0.5, the rest of fontmake-rs is on 0.0.6, and that's a compile error.
Also ... I seem to own fea-rs on [crates.io](http://crates.io/) but not have write access to the repo. Should I? Or should we make a copy under googlefonts?
> Update fontations to 0.1.0 and update fea-rs to 0.3.0 to unblock fontmake-rs

- fea-rs/src/util/pretty_diff.rs
- fea-rs/src/util/ttx.rs
This documents which string is considered the 'base' when we generated a colored diff, and uses the 'expected' result as the base when printing test failures.
> Improve diff printing

- fea-rs/src/tests/compile.rs
- fea-rs/src/util/ttx.rs
Previously we were just never running these test cases in CI, which feels bad. Now we are disabling a small number of them (which will still be run locally) and running the rest.
This means that regressions in these tests will cause us to fail CI.
> Disable some fonttools tests in CI, run the rest

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/parse/grammar/metrics.rs
- fea-rs/src/parse/grammar/mod.rs
- fea-rs/src/token_tree/typed.rs
We never got around to this because it isn't used much and it wasn't included in any of the feaLib test files that we were initially using, but it's part of the spec and is used in the latest feaLib tests.
> Support named value records (valueRecordDef)

- fea-rs/Cargo.toml
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/features.rs
- fea-rs/src/compile/tags.rs
This changed the API for constructing a tag, so I had to make some changes to accomodate that.
> Update to write-fonts 0.7, bump version to 0.7

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/token_tree/typed.rs
We were doing this in two different but equivalent ways in two different places; this standardizes that.
> Fixup parsing of OS/2 vendor tag

- fea-lsp/src/document.rs
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/parse/grammar/feature.rs
- fea-rs/src/parse/grammar/metrics.rs
- fea-rs/src/parse/grammar/mod.rs
- fea-rs/src/parse/grammar/table.rs
- fea-rs/src/parse/grammar/variations.rs
- fea-rs/src/parse/lexer.rs
- fea-rs/src/parse/lexer/lexeme.rs
- fea-rs/src/parse/lexer/token_set.rs
- fea-rs/src/parse/parser.rs
- fea-rs/src/token_tree/token.rs
- fea-rs/src/token_tree/typed.rs
- fea-rs/src/util/highlighting.rs
This is a checkpoint; we can now parse the new syntax, but we do not compile anything. It's possible that some of this code will need to change as I dig into the compilation side, but I think it's worth getting this in and working from here.
> Parse variable feature syntax

- fea-rs/src/compile/validate.rs
- fea-rs/src/parse/grammar/variations.rs
- fea-rs/src/token_tree/typed.rs
This checks for duplicate conditionset definitions, and also that any conditionsets referenced in a variation have been defined.
> Validate variation & condset blocks

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/features.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/tables.rs
We were tracking features with a BTreeMap, but for upcoming work adding support for feature variations I am going to want a richer type.
This PR is just moving things around, and contains no functional changes; I am PRing it now to avoid cluttering up subsequent PRs.
> Add AllFeatures struct

- fea-rs/src/bin/compile.rs
- fea-rs/src/compile.rs
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/compiler.rs
- fea-rs/src/compile/features.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/compile/variations.rs
- fea-rs/src/tests/compile.rs
- fea-rs/src/token_tree/typed.rs
- fea-rs/src/util/ttx.rs
This adds support for actually compiling the FeatureVariations table, based on the experimental FEA syntax.
I've learned.. so much.
I have a bunch of lingering questions about this stuff, and it now feels like an open question whether or not this syntax will make any sense in a world with avar2, but I'm not stressing that too much for now.
Computing these tables involves normalizing coordinates; I don't want fea-rs to need to worry about that, so I've added a trait that can be implemented by the compiler. This trait may need to change as we get a better understanding of the problem.
This doesn't add support for compiling variable anchors or value records, which will come next.
> Compile FeatureVariations table

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/features.rs
I don't believe this is mentioned anywhere in the spec, but it is an important detail: the sort order of conditionsets in the FeatureVariations table has meaningful impact on whether a variation is applied, since we apply the first set of variations that is encountered.
With this patch, we match the order used by fonttools, which is (as far as I can deduce) based on the order in which a given conditionset is first referenced by a lookup.
There is some behaviour in fonttools I still do not fully understand, so I will open a discussion issue there.
> Use stable ConditionSet sort order

- fea-rs/src/bin/compile.rs
- fea-rs/src/compile/compiler.rs
- fea-rs/src/tests/compile.rs
- fea-rs/src/util/ttx.rs
This is more ergonomic than just cramming it into the `new` method.
> Use builder method to pass VariationInfo to compiler

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/token_tree/typed.rs
~Based on #166.~
This adds simple validation to variable metrics, ensuring that referenced tags exist, and values are in range for those tags.
> Validate variable metrics

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/parse/grammar/gpos.rs
- fea-rs/src/token_tree/rewrite.rs
- fea-rs/src/token_tree/typed.rs
- fea-rs/test-data/compile-tests/mini-latin/good/spec_6iii_3c.fea
- fea-rs/test-data/compile-tests/mini-latin/good/spec_6iii_3c.ttx
- fea-rs/test-data/parse-tests/bad/contextual_inline_pairpos.ERR
- fea-rs/test-data/parse-tests/bad/contextual_inline_pairpos.fea
- fea-rs/test-data/parse-tests/good/spec6iii_3c.PARSE_TREE
- fea-rs/test-data/parse-tests/good/spec6iii_3c.fea
Per #170, there was a bit of syntax related to contextual GPOS rules that I was not handling correctly.
This was a rabbit hole; the spec seems to have a typo (https://github.com/adobe-type-tools/afdko/issues/1665) and it looks like this syntax isn't included in the fonttools tests, although it does handle it.
I've manually compared our output to fonttools', and we are now generating the same ttx.
relevant to this, it looks like there may be some additional inline GPOS rules that I am not correctly handling, specifically I do not handle [inline cursive](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#6hiv-specifying-contextual-positioning-with-in-line-cursive-positioning-rules) or [inline mark positioning](http://adobe-type-tools.github.io/afdko/OpenTypeFeature …
> Parse trailing paripos

- fea-rs/src/common/glyph_map.rs
- fea-rs/src/tests/compile.rs
- fea-rs/src/tests/parse.rs
- fea-rs/src/util/ttx.rs
- fea-rs/test-data/parse-tests/good/glyph_or_range.PARSE_TREE
- fea-rs/test-data/parse-tests/good/glyph_or_range.fea
Another thing motivated by investigating #170; it seems like ambiguous tokens are persisting after where I would expect, so I wanted to improve the testing of this.
- A glyph range is specified with the syntax 'a - z', where the spaces around the hyphen are optional.
- A hyphen is a valid character in a glyph name
- Ergo, 'a-z' could either be the range of glyphs from 'a' to 'z', or the name of a single glyph, 'a-z'.
- In order to parse this correctly, you need a list of glyph names.
I have other tests for this, but I didn't have an integration test, and in the course of adding it I discovered that,
- the sample glyph list we use (taken from what fonttools uses) was included in two places. So I fixed that.
- the parse tests were not currently passing in a glyph map at all; now they are.
- …
> Add full parse test for glyph/range disambiguation

- fea-rs/src/parse/grammar/gpos.rs
Two things happened:
- In 492cedc I commited a test case that I was just using to debug, and which checks behaviour that I have added other tests for,
- and in 659efcc I renamed a function that was called from that test case.
> Fix breakage from merge

- fea-rs/Cargo.toml
This will let us update fontc, so that the everyone can see the current errors produced on problem fonts.
> Bump version to 0.8.1

- fea-rs/src/util/ttx.rs
I call a function that loads a file from a relative path. It is called two different ways; either when running `cargo test`, or when running the ttx_test binary.
`cargo test` runs tests for a given crate from that crate's root directory, but cargo run --bin=x can be run from the crate root; so I need to ensure that I use the correct relative for both of these cases.
I really don't know what the principled approach to this is, outside of baking the file into the binary at compile time? But this at least fixes my concrete problem.
> Fixup loading of test-data for non-tests

- fea-rs/src/compile/validate.rs
- fea-rs/test-data/compile-tests/mini-latin/bad/lookup_multiple_flags.fea
A single lookup can only contain rules with a single lookupflag; our previous validation pass errored anytime a lookupflag statement occured after a rule, but this misses the case where a lookupflag statement occurs after the last rule, and thus is not applied to any rule in the containing lookup.
This was one of the issues in #170.
> Tweak validation behaviour of redefined lookupflags

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/gsub.rs
- fea-rs/src/compile/validate.rs
- fea-rs/test-data/compile-tests/mini-latin/good/gpos_mixed_single_multi_rules.fea
- fea-rs/test-data/compile-tests/mini-latin/good/gpos_mixed_single_multi_rules.ttx
- fea-rs/test-data/compile-tests/mini-latin/good/gsub1.fea
- fea-rs/test-data/compile-tests/mini-latin/good/gsub1.ttx
In the case where a lookup contains mixed Single and Multiple Substitution rules, we will combine them all into a single Multiple substitution lookup.
This matches the behaviour of fonttools, and has nominal blessing from adobe (https://github.com/adobe-type-tools/afdko/issues/224#issuecomment-537215163) although that has not made it into the spec.
- fixes #180
- last work for #170
> Support mixed GSUB Type 1 and Type 2 rules

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/tables.rs
- fea-rs/src/compile/tables/gdef.rs
- fea-rs/src/compile/variations.rs
- fea-rs/src/token_tree/typed.rs
This is a MVP-type sketch of something that passes variable metrics to the compiler for resolution.
The compiler would be required to implement the `VariationInfo` trait, defined in compile/variations.rs; in particular the `resolve_variable_metric` method.
@rsheeter this is the barest-bones interface I can imagine. As much as possible I am avoiding custom types, in favour of types in `write-fonts`. It isn't currently hooked up to anything; in addition to needing to wire this up to whatever is computing the deltas, I'll also need to implement something to build the final ItemVariationStore.
> Sketch out API for getting deltas from the compiler

- fea-rs/src/compile/valuerecordext.rs
In general when a value record contains a 0 value for an advance or placement, we want to treat this as "no value", since this lets us more efficiently pack the data.
In the case of a variable font, however, it is entirely possible for a value record to have a default value of 0. In this case we want to leave this field in the record.
I'm not 100% sure this makes sense, since if the implementation is variable- aware it can compute the correct value, and if it isn't it shouldn't matter? But erring on the side of "do what fonttools does, for now."
cc @anthrotype, do you have any insight into this?
> More careful zeroing of value records

- fea-rs/Cargo.toml
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/tables.rs
- fea-rs/src/compile/tables/gdef.rs
- fea-rs/src/compile/tables/var_store.rs
This is barebones: it only stores short values (no COLR support) and it does zero optimization; we can work on that after.
This gets everything wired up, but is missing the part where you remap the values at the end.
All the logic is in `var_store.rs`, everything else is just glue.
> First pass at a VarStoreBuilder

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/lookups/gpos.rs
- fea-rs/src/compile/tables/var_store.rs
This implements that logic that goes through every item that may contain a reference to something in the ItemVariationStore, and replaces the temporary VariationIndex with the appropriate index in the compiled table.
Based on #185, which should go in first.
> Remap VarStore references after compilation

- fea-rs/src/compile/tables/var_store.rs
This is an attempt at an idiomatic Rust implementation of the [`VarStore_optimize`](https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/varLib/varStore.py#L471) function from fonttools.
This ends up being quite a bit of code, and required a bunch of structural changes to the original design, but I'm overall happy with the result. 
There's one main todo, which is to figure out how to adapt the tests from fonttools.
- based on #185, which should go in first.
> Optimize VarStore builder

- fea-rs/src/compile/lookups/gpos.rs
This fixes a long standing (but previously unencountered) issue where we could not write empty value records containing device or variation index tables.
This required an upstream fix, which is now in place.
> Correctly write empty value records

- fea-rs/Cargo.toml
- fea-rs/src/bin/compile.rs
- fea-rs/src/compile.rs
These are only necessary if fea-rs is run as a binary from the command line, and we expect in the general case that it will be used as a library; no need to be compiling these two dependencies in that case.
> Put clap & norad behind 'cli' feature

- fea-rs/src/compile/compiler.rs
the CI won't detect it though as it apparently is not running the doctests AFAIU
> Fix failing doctest in compile/compiler.rs

- fea-rs/Cargo.toml
required to be able to depend on it from fontc, fixes a few issues with IUP optimization which should not affect fea-rs itself
> bump write-fonts to 0.14.0

- .github/workflows/rust.yml
apparently --all-targets doesn't work with doctests, so we run a bare `cargo test` as well.
> [ci] Ensure doctests run in CI

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups.rs
- fea-rs/src/compile/tables/var_store.rs
Just a draft for now, can be merged if https://github.com/googlefonts/fontations/pull/544 makes it into a release.
----
This is a more principled way of ensuring that we correctly remap all of these values before the final compilation pass.
> Use the PendingVariationIndex table instead of DeltaKey

- fea-rs/src/compile/tables/gdef.rs
we don't bother building a GDEF table if it will be empty, but we had not updated the is_empty check to consider the possibile existence of item variation data, and so we were not building GDEF in a situation where this subtable (and no others) was present.
We should add some integration tests that involve building this table, but that requires us to have some way to locally wire up the VariationModel.
> Check for VarStore in GDEF when deciding to build

- fea-rs/src/compile.rs
- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/compile/variations.rs
- fea-rs/src/parse/grammar/metrics.rs
- fea-rs/src/parse/lexer.rs
- fea-rs/src/parse/lexer/lexeme.rs
- fea-rs/src/token_tree/token.rs
- fea-rs/src/token_tree/typed.rs
- fea-rs/test-data/compile-tests/mini-latin/bad/variable_value_record_oob.ERR
- fea-rs/test-data/compile-tests/mini-latin/bad/variable_value_record_oob.fea
- fea-rs/test-data/parse-tests/bad/suffix_metrics.ERR
- fea-rs/test-data/parse-tests/bad/suffix_metrics.fea
- fea-rs/test-data/parse-tests/good/suffix_metrics.PARSE_TREE
- fea-rs/test-data/parse-tests/good/suffix_metrics.fea
- fea-rs/test-data/parse-tests/good/variable_anchor.PARSE_TREE
- fea-rs/test-data/parse-tests/good/variable_metrics.PARSE_TREE
- fea-rs/test-data/parse-tests/good/variable_value_record.PARSE_TREE
This was much less painful than I had expected! When I had been thinking about this change I was thinking that the unit suffixes would be applied to the metric values themselves, which are used all over the place (including in non-variable contexts) but in reality the suffixes only apply to the values for the axis positions, which means that we can parse them differently without that impacting the parsing of anything else in the codebase.
@rsheeter this shouldn't require much change for you; the main difference is that instead of using a 'user location' we now use a location where the values are an enum with user/design/normalized variants.
> Support axis location unit suffixes

- fea-rs/src/bin/ttx_test.rs
- fea-rs/src/compile/lookups/contextual.rs
This moves a few things around, adds logging, and minorly improves the efficiency of compilation in the case where only one table format is possible (by not bothering to precheck the sizes in this case.)
> Minor refactor of contextual lookup compilation

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/lookups/contextual.rs
This resolves one more outstanding diff with fonttools, which is represented in the 'bug514.fea' test case; when adding anonymous rules we would only ever check the most recently added anonymous lookup to see if rules could be inserted there. With this change we will now check all active anonymous lookups, which means we should create fewer lookups and have fewer redundencies in them.
> More efficient generation of anonymous lookups

- fea-rs/src/util/ttx.rs
This can go in once #212 #208 and #206 are merged.
----
This was gross; the idea was that we had certain known failures in the fonttools test suite, but we wanted to run the rest of those cases for the time being, so would explicitly check to see if we were in CI when running tests.
This was probably too cute. In any case there are now PRs up that resolve these outstanding failures, so we can get rid of this.
> [ci] Remove code to ignore certain test cases in CI

- fea-rs/test-data/parse-tests/good/valuerecord_formats.PARSE_TREE
- fea-rs/test-data/parse-tests/good/valuerecord_formats.fea
We didn't support named value records for a while, and so this had been omitted, but support was added a few months ago.
> Remove commented out value record format test case

- fea-rs/Cargo.toml
- fea-rs/src/compile/validate.rs
- fea-rs/src/compile/variations.rs
- fea-rs/src/token_tree/typed.rs
This will hopefully reduce the chance that we run into differences when reading/writing string values.
> Store AxisLocation as f32, not Fixed

- fea-rs/src/compile/lookups/contextual.rs
This was cluttering up logs when I was debugging pairpos2 splitting.
> Change format size log level to 'trace'

- fea-rs/src/compile/tables/var_store.rs
I'm not sure if this was triggerable during real use, but I was hitting it in some test code where we don't have a real variation model, and so were passing empty deltas.
> Fix crash when trying to write all-zero deltas

- fea-rs/src/compile/compile_ctx.rs
- fea-rs/src/compile/validate.rs
- fea-rs/src/parse/grammar/feature.rs
- fea-rs/src/parse/parser.rs
- fea-rs/src/token_tree.rs
- fea-rs/test-data/compile-tests/mini-latin/good/naked_semi.fea
- fea-rs/test-data/compile-tests/mini-latin/good/naked_semi.ttx
- fea-rs/test-data/parse-tests/good/naked_semi_in_lookup.PARSE_TREE
- fea-rs/test-data/parse-tests/good/naked_semi_in_lookup.fea
This matches the behaviour of fontmake, although it deviates from makeotf.
Motivated by https://github.com/googlefonts/fontc/issues/436
> Accept naked semi ('null statements')

- fea-rs/Cargo.toml
Not directly needed by fea-rs but fontc (user of fea-rs) needs it and can't update otherwise
> bump write-fonts to 0.17.0

- fea-rs/Cargo.toml
bump minor because write-fonts was bumped minor
No actual changes besides bumping write-fonts itself
> bump minor version to 0.18

- fea-rs/src/bin/compile.rs
- fea-rs/src/compile.rs
- fea-rs/src/compile/variations.rs
This will make it easier for us to debug and profile fontc, by letting us run feature compilation in isolation, on our real inputs.
axis info can be specified in a file, where each (non blank, non commented) line contains a tag and three numbers.
I thought about various ways this could be specified, and this just felt like the simplest, although I don't particularly like it.
The idea here is that (as discussed with @rsheeter at some point) is that it would be nice for both profiling and debugging fontc if we could dump out our generated fea and our axis info and then run the feature compiler directly.
> Allow specifying variation info at the CLI
