fea-rs/Cargo.toml, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/tables.rs, fea-rs/src/compile/validate.rs, fea-rs/src/parse/grammar/table.rs, fea-rs/src/token_tree/typed.rs, fea-rs/src/util/ttx.rs
parsing, validation & compilation (where possible)
=> Hhea vhea name

fea-rs/src/parse.rs, fea-rs/src/parse/grammar/feature.rs, fea-rs/src/parse/grammar/mod.rs, fea-rs/src/parse/lexer.rs, fea-rs/src/parse/token.rs, fea-rs/src/token_tree.rs, fea-rs/src/util/highlighting.rs
This adds some parse tests to handle cases I found in a bunch of scraped FEA, and tries to fix the underlying problems.
=> More parse tests

fea-rs/src/util/ttx.rs
This is a very basic thing but it lets me know what tests are failing
because of some small difference, and what ones are just miles away.
=> Show diff percentage in summary of ttx tests

fea-rs/src/parse/source.rs, fea-rs/src/util/highlighting.rs
This rips off the basic appearance of the current rust diagnostics,
although we (currently) do not have as many features or display options.
=> Fancier diagnostics

fea-rs/Cargo.toml, fea-rs/src/compile.rs, fea-rs/src/compile/common.rs, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/consts.rs, fea-rs/src/compile/lookups.rs, fea-rs/src/compile/output.rs, fea-rs/src/compile/tables.rs, fea-rs/src/compile/validate.rs
This started out as a branch where i was working on the ss[01-20] and cv[01-99] features, but in the process of that work I did a bunch of refactoring that can be PR'd alone.
=> Rationalize name building

fea-rs/src/compile/common.rs, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/output.rs, fea-rs/src/compile/tables.rs, fea-rs/src/compile/validate.rs, fea-rs/src/parse/grammar/feature.rs, fea-rs/src/token_tree/token.rs, fea-rs/src/token_tree/typed.rs
This involves handling the special syntax used to declare the feature params for these features.
=> Handle ss01-20, cv01-99 feature blocks

fea-rs/src/compile/tables.rs
This updates our logic to better match how the behaviour of feaLib,
which I think is valuable for the time being while we use the feaLib
test suite as our benchmark.
=> Fix STAT compilation

fea-rs/Cargo.toml, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/output.rs, fea-rs/src/compile/tables.rs, fea-rs/src/token_tree/typed.rs
This adds compilation for the base table. It depends on https://github.com/googlefonts/fontations/pull/170, and shouldn't be merged until that is, and i double check that the git sha I am pinned to here is still valid.
closes #46
=> Compile BASE table

fea-rs/Cargo.toml, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/output.rs, fea-rs/src/compile/tables.rs, fea-rs/src/compile/validate.rs
This was blocked on upstream support.
=> Compile OS/2 table

fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/lookups/gsub.rs, fea-rs/src/compile/output.rs
This is two small patches that are fixing up issues that had been lost in the noise of various other ongoing failures in our diff tests.
=> Fix incorrect delta calculation in GSUB1 and not setting name id in size feature params

fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/lookups.rs, fea-rs/src/compile/output.rs
Another little thing we hadn't gotten around to initially.
=> Add support for specifying required features

fea-rs/src/compile/lookups/gpos.rs
=> Rework GPOS1 subtable compilation logic

fea-rs/Cargo.toml, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/lookups.rs, fea-rs/src/compile/lookups/gpos.rs, fea-rs/src/compile/lookups/helpers.rs, fea-rs/src/types.rs
This now matches the behaviour of feaLib
=> Rework GPOS2 compilation

fea-rs/Cargo.toml
Doesn't break anything,  but i'd like the new into_iter behaviour.
=> Update to 2021 edition

fea-rs/src/compile/lookups/helpers.rs
To whit: longer classes first (we were doing this) and then break ties by prefering the class containing the lower glyph id (we were doing the opposite)
=> Match feaLib glyph class assignment

fea-rs/src/compile.rs, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/features.rs, fea-rs/src/compile/output.rs
This is only moving things around; compile_ctx.rs is huge, and I would like to add additional helper types related to tracking features in the near future.
=> Add compile::features module

fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/lookups.rs
This combines the flag and the current mark filter set into a single struct, since they are only ever used or manipulated together.
=> Refactor lookupflag tracking

fea-rs/Cargo.toml, fea-rs/src/bin/compile.rs, fea-rs/src/bin/ttx_test.rs
Clap is more flexible and more familiar.
=> Use clap instead of xflags for CLI args

LICENSE-APACHE, LICENSE-MIT, README.md, fea-rs/Cargo.toml, fea-rs/src/bin/compile.rs, fea-rs/src/types.rs
This bumps us to 0.1.0, as we are ready for a *real release*!?
This also adds badges to the readme, and brings the license files into the repo.
Also we're now dual MIT/Apache instead of just Apache.
=> Prepare for release, add license files

fea-rs/src/bin/compile.rs, fea-rs/src/compile.rs, fea-rs/src/compile/output.rs, fea-rs/src/tests/compile.rs
This adds the ability to pass an existing font to be used as the source for the glyph order. This option also exists for feaLib and afdko, which makes it easier for me to run all three tools against a given input, to compare results.
=> Compile with font as glyph order source

fea-rs/src/tests/compile.rs
This seems like a reasonable simplification, and will make it easier to inspect the glyph order being used.
=> Tests store glyph order as text instead of in font

fea-rs/src/compile/compile_ctx.rs
=> Deduplicate lookups

fea-rs/src/compile/compile_ctx.rs, fea-rs/src/tests/compile.rs, fea-rs/src/util/ttx.rs
We were previously only testing that it parsed correctly.
=> Test that file with includes compiles correctly

fea-rs/src/bin/compile.rs, fea-rs/src/bin/parse_test.rs, fea-rs/src/compile/lookups.rs, fea-rs/src/compile/validate.rs, fea-rs/src/parse.rs, fea-rs/src/parse/context.rs, fea-rs/src/parse/grammar/gpos.rs, fea-rs/src/parse/grammar/mod.rs, fea-rs/src/token_tree.rs, fea-rs/src/token_tree/edit.rs, fea-rs/src/util/ttx.rs
- removal of ParseContext from public API
- removing some old fixmes
- removing some types from the public API
=> Minor cleanup

fea-lsp/Cargo.toml, fea-rs/Cargo.toml
=> Set version to 0.2.0, update some deps

fea-rs/src/parse/source.rs, fea-rs/src/util/paths.rs
Fixes https://github.com/cmyr/fea-rs/issues/127
=> rebase_path can assume the current directory when base is empty ''

fea-rs/Cargo.toml, fea-rs/src/compile/error.rs, fea-rs/src/compile/tables.rs
Next step after https://github.com/googlefonts/fontations/pull/403. Trying to make fontmake-rs work against fontations latest so I can use iup.
=> Update to latest write-fonts

fea-rs/src/parse/grammar/feature.rs
Pulling this out of another PR to make sure it didn't cause any test failures.
=> Improve accuracy of parse error diagnostic

fea-rs/src/util/ttx.rs
In our reuse of the fonttools test suite, we have a mechanism whereby we can indicate that certain diffs in our ttx are acceptable; for instance in some places we may choose not to implement a given feature, to choose a different table format, or otherwise produce a binary that is acceptable but is not *exactly* what fonttools produces.
Previously, if there was an expected diff for a given input, but we produced output identical to fonttools, we would succeed. This means that we had a bunch of expected diffs sitting around that were never actually used.
With this change, we will now fail a given test case if there is an expected diff, but our output is identical to fonttools.
In addition, we now ignore comments when comparing these diffs; I would like to adopt the convention that the …
=> Always check for expected diff in ttx tests

fea-rs/src/compile/features.rs, fea-rs/src/compile/lookups.rs
This will be reused for variations stuff.
=> Move lookup splitting logic into features.rs

fea-rs/src/parse/grammar/metrics.rs
This now enforces the constraint that there is at least one location/value pair specified, and that the location contains at least one axis.
=> More rigorous variable metric parsing

fea-rs/src/compile/compile_ctx.rs
Hopefully this will provide a bit more (ahem) *context* for anyone trying to figure out what's going on here.
=> Improve docs in compile_ctx.rs

fea-rs/src/parse/grammar/feature.rs, fea-rs/src/parse/grammar/gpos.rs, fea-rs/src/parse/grammar/gsub.rs, fea-rs/src/parse/grammar/mod.rs, fea-rs/src/token_tree.rs, fea-rs/src/token_tree/edit.rs
A few small changes to try and make things more intelligible, after working on grammar stuff for the first time in a while.
=> Clarify some function names, improve comments

fea-rs/Cargo.toml, fea-rs/src/compile/compile_ctx.rs, fea-rs/src/compile/valuerecordext.rs
This also updates write-fonts; we'll need to do a release here too, but I'd like to wait until everything lands?
=> Use ValueRecord builder methods

fea-rs/Cargo.toml, fea-rs/src/compile/error.rs, fea-rs/src/compile/output.rs
This is blocked until we get a new version of write-fonts.
This will also need to be updated to include the 'read' feature.
=> Update for new FontBuilder API

fea-rs/test-data/fonttools-tests/spec5f_ii_3.expected_diff
We are generating the same binary as makeotf, and I believe fonttools is generating a less efficient result.
=> Mark fonttools diff for spec5f_ii_3 as ok

fea-rs/src/parse/grammar/metrics.rs, fea-rs/test-data/compile-tests/mini-latin/good/big_device.fea, fea-rs/test-data/compile-tests/mini-latin/good/big_device.ttx
=> Ensure we compile arbitrarily long device records

fea-rs/src/compile/tables/name.rs, fea-rs/src/compile/validate.rs, fea-rs/src/parse/lexer.rs
=> [clippy] Push the rock back up the hill

fea-rs/src/bin/compile.rs
This makes it infinitely easier to figure out what's wrong when you provide an incorrect path.
based on #238, so on hold until that is (or isn't) merged
=> Include path when reporting IO errors
